### ISSUE TITLE
Build fails after upgrading to 0.14.3 from 0.13.3

### ISSUE THREAD

**Issue by SergiOnGit** [unimodules/react-native-unimodules#172]
It shows two error:

```
require(expo-modules-autolinking)(process.argv.slice(1))
        ^
ReferenceError: expo is not defined
```

And

```
error: cannot find symbol
    mModuleRegistryProvider = new ReactModuleRegistryProvider(new ExpoModulesPackageList().getPackageList(), null);
                                                                  ^
  symbol:   class ExpoModulesPackageList
  location: class ModuleRegistryAdapter
```

Node version: 14.17.2
React native version: 0.64.2

If I downgrade to 0.13.3 it works, but I want latest version.

Any help?

**Comment by Albermonte** [comment]
Same error here, just updated from Expo SDK 41 to 42 and this two errors are showing now.

Node version: v14.17.0
React Native version: v0.63.4

**Comment by nyabongoedgar** [comment]
I have the same issue, has anyone solved this ?
"dependencies": {
    "react": "17.0.1",
    "react-native": "0.64.1"
  }

**Comment by Albermonte** [comment]
It was solved in https://github.com/expo/expo/issues/13475

**Comment by byCedric** [comment]
It's solved, but not yet released. You can use the temporary patch [described in this comment](https://github.com/expo/expo/issues/13475#issuecomment-874143200). When the fix is released, I'll mention it here and close this issue.

**Comment by SergiOnGit** [comment]
@Albermonte What is the fix? I see they change code in node_modules, that can't be considered as fix.

**Comment by byCedric** [comment]
@SergiOnGit this is the fix https://github.com/expo/expo/pull/13494

**Comment by byCedric** [comment]
See https://github.com/expo/expo/issues/13475#issuecomment-874794423

> Patch has been released! Please use `@unimodules/react-native-adapter@6.3.2` (`latest`). If you want to check your local version:
>
> - `$ yarn why @unimodules/react-native-adapter`
> - `$ npm list @unimodules/react-native-adapter`
>
> It should be installed automatically, but if it doesn't make sure to regenerate your lockfile.

**Comment by simondelacourt** [comment]
@byCedric I am not sure if thats the fix;

`> Task :unimodules-react-native-adapter:compileDebugJavaWithJavac FAILED
/Users/simondelacourt/projects/glance-mobile/node_modules/@unimodules/react-native-adapter/android/src/main/java/org/unimodules/adapters/react/ModuleRegistryAdapter.java:26: error: cannot find symbol
    mModuleRegistryProvider = new ReactModuleRegistryProvider(new ExpoModulesPackageList().getPackageList(), null);
                                                                  ^
  symbol:   class ExpoModulesPackageList
  location: class ModuleRegistryAdapter
1 error

`

`❯ npm list @unimodules/react-native-adapter
@1.4.0 /Users/simondelacourt/projects/glance-mobile
├─┬ expo@42.0.0
│ └── @unimodules/react-native-adapter@6.3.2
└─┬ react-native-unimodules@0.14.3
  └── @unimodules/react-native-adapter@6.3.2  deduped`

**Comment by byCedric** [comment]
try fully rebuilding with gradle

**Comment by simondelacourt** [comment]
Hi @byCedric I notice that your patch has been applied, but I am still unable to build the application. I've cleaned caches, cleaned the project, but I still end up at exactly the same error. The build is failing both on my local Macbook as well as on AppCenter. 

If you have any ideas where as to look, that would be great! Thanks in advance

**Comment by byCedric** [comment]
If it's failing on your macbook, it's not related to the fix we sent out. That one is related to Windows only. I would [recommend reading through this comment](https://github.com/expo/expo/issues/13475#issuecomment-875526025) and see if this is the exact error you are running into as well.

**Comment by simondelacourt** [comment]
@byCedric thanks/dankje for the help, it seems to be caused by me accidentally running Node 12, and switching it 14 does the trick on the macbook.

**Comment by byCedric** [comment]
Geen probleem :) That's something we have to be careful about next time, Node 12 is in maintenance mode and Node 14 is the active current LTS. We will always support the active LTS, but we probably need to warn/validate that version too.

**Comment by SergiOnGit** [comment]
I can confirm that the issue is fixed now.

**Comment by vsalguero** [comment]
It was solve in https://github.com/expo/expo/issues/13475#issuecomment-874143200
